# Generated by Django 3.1 on 2023-02-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_singup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcm_token',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='fcm_token',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fcm_token',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
    ]
